---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
        interval: "daily"
        time: "15:30"

  - package-ecosystem: "terraform"
    directory: "/vpc"
    schedule:
      interval: "daily"
      time: "15:30"
